### ISSUE TITLE
Doesn't work with "@supports"

### ISSUE THREAD

**Issue by tmccarten** [jonkemp/gulp-cssbeautify#7] opened 2018-10-30 15:32 UTC
Seems to malfunction on "@supports".

**Comment by jonkemp** [comment] 2018-10-30 17:48
Ah yeah, this plugin relies on the cssbeautify module which looks like it is no longer supported.

https://github.com/senchalabs/cssbeautify

One option would be to fork it. A better option might be to find some replacement module that is actually being maintained.

**Comment by jonkemp** [comment] 2018-11-03 13:14
@tmccarten I wrote a simple test for this and it passed. So I need some more information from you on how this is breaking. The instructions below might help:

This looks like a bug report. In order to be as helpful as possible, here are some guidelines for bug reports:

1. **Use the GitHub issue search** &mdash; check if the issue has already been reported.

2. **Check if the issue has been fixed** &mdash; try to reproduce it using the latest `master` or development branch in the repository.

3. **Isolate the problem** &mdash; create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/) and a live example.

A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs. Thanks!

**Comment by jonkemp** [comment] 2018-11-05 14:43
The test I wrote covers the following:

```
        var input = [
            '@supports (box-shadow: 2px 2px 2px black) {',
            '  body {',
            '    background: green;',
            '  }',
            '}}',
            '@supports (display: grid) {',
            '  body {',
            '    background: green;',
            '  }',
            '}}',
            '@supports (transform-origin: 5% 5%) {',
            '  body {',
            '    background: green;',
            '  }',
            '}}',
            '@supports selector(A > B) {',
            '  body {',
            '    background: green;',
            '  }',
            '}}',
            '@supports not (transform-origin: 10em 10em 10em) {',
            '  body {',
            '    background: green;',
            '  }',
            '}}',
            '@supports (display: table-cell) and (display: list-item) {',
            '  body {',
            '    background: green;',
            '  }',
            '}}',
            '@supports (transform-style: preserve) or (-moz-transform-style: preserve) {',
            '  body {',
            '    background: green;',
            '  }',
            '}}'
        ];
```

That's a pretty comprehensive test for CSS feature queries as far as I'm concerned. The test is passing. So until I get more information, I'm closing this.

**Closed by jonkemp** 2018-11-05 14:43 UTC
Labels: bug
